services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: unless-stopped
    ports:
      - "9080:9080"
      - "9443:9443"
    volumes:
      - "./traefik/letsencrypt:/letsencrypt"
      - "./traefik/logs:/var/log/traefik"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck" ]
      interval: 5s
      timeout: 2s
      retries: 3

networks:
  traefik:
    external: true