services:
  kub-postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: kub-postgres
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: |
      postgres \
      -c max_connections=200 \
      -c shared_buffers=2GB \
      -c effective_cache_size=6GB \
      -c maintenance_work_mem=512MB \
      -c checkpoint_completion_target=0.9 \
      -c wal_buffers=16MB \
      -c default_statistics_target=100 \
      -c random_page_cost=1.1 \
      -c effective_io_concurrency=200 \
      -c work_mem=1310kB \
      -c huge_pages=off \
      -c min_wal_size=1GB \
      -c max_wal_size=4GB \
      -c max_worker_processes=4 \
      -c max_parallel_workers_per_gather=2 \
      -c max_parallel_workers=4 \
      -c max_parallel_maintenance_workers=2 \

    healthcheck:
      test: [ "CMD", "pg_isready" ]