services:
  headscale:
    image: headscale/headscale:v0.23.0-alpha12
    container_name: headscale
    restart: unless-stopped
    entrypoint: headscale serve
    environment:
      HEADSCALE_OIDC_CLIENT_SECRET: ${HEADSCALE_OIDC_CLIENT_SECRET}
    volumes:
      - ./config:/etc/headscale
    ports:
      - "3478:3478"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "headscale", "users", "list"]
      interval: 30s
      timeout: 10s
      retries: 3

  headscale-fixxer:
    image: ghcr.io/ozeliurs/k3s-headscale-route-manager:latest
    container_name: headscale-fixxer
    restart: unless-stopped
    environment:
      API_URL: "http://headscale.apoorva64.com:8080/api/v1"
      API_KEY: ${HEADSCALE_API_KEY}
